# #!/usr/bin/env bash
# set -euo pipefail

# ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# export NUM_GPUS="${NUM_GPUS:-2}"
# export ROLLOUT_TP="${ROLLOUT_TP:-1}"
# export TEACHER_TP="${TEACHER_TP:-1}"
# export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-64}"
# export MICRO_BATCH_SIZE="${MICRO_BATCH_SIZE:-8}"
# export PPO_MAX_TOKEN_LEN_PER_GPU="${PPO_MAX_TOKEN_LEN_PER_GPU:-98304}"
# export MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-2048}"
# export MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-1024}"
# export ROLLOUT_MAX_MODEL_LEN="${ROLLOUT_MAX_MODEL_LEN:-3072}"
# export TEACHER_MAX_MODEL_LEN="${TEACHER_MAX_MODEL_LEN:-6144}"
# export ROLLOUT_MAX_BATCHED_TOKENS="${ROLLOUT_MAX_BATCHED_TOKENS:-98304}"
# export TEACHER_MAX_BATCHED_TOKENS="${TEACHER_MAX_BATCHED_TOKENS:-114688}"
# export ROLLOUT_GPU_MEMORY_UTILIZATION="${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.65}"
# export TEACHER_GPU_MEMORY_UTILIZATION="${TEACHER_GPU_MEMORY_UTILIZATION:-0.60}"
# export ROLLOUT_AGENT_NUM_WORKERS="${ROLLOUT_AGENT_NUM_WORKERS:-16}"
# export REWARD_NUM_WORKERS="${REWARD_NUM_WORKERS:-16}"
# export DATALOADER_NUM_WORKERS="${DATALOADER_NUM_WORKERS:-16}"
# export ACTOR_PARAM_OFFLOAD="${ACTOR_PARAM_OFFLOAD:-False}"
# export ACTOR_OPTIMIZER_OFFLOAD="${ACTOR_OPTIMIZER_OFFLOAD:-False}"
# export REF_PARAM_OFFLOAD="${REF_PARAM_OFFLOAD:-False}"
# export VAL_BEFORE_TRAIN="${VAL_BEFORE_TRAIN:-false}"
# export TOTAL_EPOCHS="${TOTAL_EPOCHS:-2}"
# export SAVE_FREQ="${SAVE_FREQ:-200}"
# export TEST_FREQ="${TEST_FREQ:-200}"

# bash "${ROOT_DIR}/scripts/run_opsd_4b_verl.sh"


#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export NUM_GPUS="${NUM_GPUS:-2}"
export ROLLOUT_TP="${ROLLOUT_TP:-1}"
export TEACHER_TP="${TEACHER_TP:-1}"
export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-32}"
export MICRO_BATCH_SIZE="${MICRO_BATCH_SIZE:-6}"
export PPO_MAX_TOKEN_LEN_PER_GPU="${PPO_MAX_TOKEN_LEN_PER_GPU:-73728}"
export MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-2048}"
export MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-1024}"
export ROLLOUT_MAX_MODEL_LEN="${ROLLOUT_MAX_MODEL_LEN:-3072}"
export TEACHER_MAX_MODEL_LEN="${TEACHER_MAX_MODEL_LEN:-6144}"
export ROLLOUT_MAX_BATCHED_TOKENS="${ROLLOUT_MAX_BATCHED_TOKENS:-65536}"
export TEACHER_MAX_BATCHED_TOKENS="${TEACHER_MAX_BATCHED_TOKENS:-73728}"
export ROLLOUT_GPU_MEMORY_UTILIZATION="${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.70}"
export TEACHER_GPU_MEMORY_UTILIZATION="${TEACHER_GPU_MEMORY_UTILIZATION:-0.65}"
export ROLLOUT_AGENT_NUM_WORKERS="${ROLLOUT_AGENT_NUM_WORKERS:-16}"
export REWARD_NUM_WORKERS="${REWARD_NUM_WORKERS:-16}"
export DATALOADER_NUM_WORKERS="${DATALOADER_NUM_WORKERS:-16}"
export ACTOR_PARAM_OFFLOAD="${ACTOR_PARAM_OFFLOAD:-False}"
export ACTOR_OPTIMIZER_OFFLOAD="${ACTOR_OPTIMIZER_OFFLOAD:-False}"
export REF_PARAM_OFFLOAD="${REF_PARAM_OFFLOAD:-False}"
export VAL_BEFORE_TRAIN="${VAL_BEFORE_TRAIN:-false}"
export TOTAL_EPOCHS="${TOTAL_EPOCHS:-1}"
export SAVE_FREQ="${SAVE_FREQ:-200}"
export TEST_FREQ="${TEST_FREQ:-200}"

bash "${ROOT_DIR}/scripts/run_opsd_4b_verl.sh"

